name: Bug Report
description: File a bug report
labels: [bug, "Triage Needed"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: input
    id: os_version
    attributes:
      label: Operating system
  - type: input
    id: python_version
    attributes:
      label: Python version
      description:  Your python version`python -v`
    validations:
      required: true
  - type: input
    id: ccxt_version
    attributes:
      label: CCXT Version 
      description: CCXT Version (`pip freeze | grep ccxt`)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version you running? (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Also tell us, what did you expect to happen? 
        How can we reporoduce this issue?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
