name: Test CI

on:
  push:
    branches:
      - master
  release:
    types: [published]
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: test show all 
      run: |
        set

    - name: show github config
      run: |
        cat ${GITHUB_EVENT_PATH}

    - name: create_asset
      run: echo "hello world" > hello_world.txt
    
    - uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release'
      with:
        files: 'hello_world.txt'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  
  
