name: Test CI

on:
  push:
    branches:
      - master
  release:
    types: [published]
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: test show all 
      run: |
        set

    - name: show github config
      run: |
        cat ${GITHUB_EVENT_PATH}

    - name: create_asset
      run: echo "hello world" > hello_world.txt && echo "hello world2" > hello_world2.txt
    
#     - uses: AButler/upload-release-assets@v2.0
#       if: github.event_name == 'release'
#       with:
#         files: 'hello_world*.txt'
#         repo-token: ${{ secrets.GITHUB_TOKEN }}

#     - name: Upload release binaries
#       uses: alexellis/upload-assets@0.2.2
#       if: github.event_name == 'release'
#       env:
#         GITHUB_TOKEN: ${{ github.token }}
#       with:
#         asset_paths: '["hello_world*.txt"]'
  
# Following did NOT work!
#     - uses: shogo82148/actions-upload-release-asset@v1
#       if: github.event_name == 'release'
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: hello_world*.txt
#         asset_name: hello_worlds.zip

    - name: Upload Release Asset
      id: upload-release-asset 
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./hello_world*.txt
        asset_name: hello_world.zip
        asset_content_type: application/zip
