name: Test CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  release:
    types: [published]
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: test show all 
      run: |
        set

    - name: show github config
      run: |
        cat ${GITHUB_EVENT_PATH}
