name: Test python install

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
 test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04 ]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      if: "${{ matrix.python-version != '3.10' }}"
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true


    # - name: Verify PIP
    #   run: |
    #     pip install -U pip
    #     echo "Python version"
    #     python --version
    #     python -c 'import sysconfig;print(f"sysconfig: {sysconfig.get_platform()}")'
    #     python -c 'from pip._vendor.distlib.util import get_host_platform; print(f"pip gethost: {get_host_platform()}")'
    #     echo "---"
    #     pip install catboost==1.2


    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: false
        # cache-suffix: "${{ matrix.python-version }}"
        # prune-cache: false

    - name: "ls"
      run: |
        ls -l .
        which python3
        python3 -VV
        uv python list

    - name: "install torch"
      run: |
        # uv venv
        # . .venv/bin/activate
        uv pip install torch

    - name: "run cache ls"
      run: |
        ls -l ${UV_CACHE_DIR}
        tree ${UV_CACHE_DIR}

